### PR TITLE
Run unittest on appveyor.

### PR DESCRIPTION
**Pull request by zwn**

### CODE REVIEW

**Comment by zwn** [comment]
When you merge this, can you try to use the "squash & merge" option from the github UI?

**Comment by m3d** [comment]
Is this extra unittesting really needed?

**Comment by zwn** [comment]
Right now it not *really* needed but when we start doing automatic tests using headless Speed Dreams I see the value in having both Linux and Windows versions.

**Comment by m3d** [comment]
OK, thanks for explanation - I was not aware of platform differences ...

**Pull request merged**
