### PR TITLE
Compute the nearest segment for the whole track

### PR DESCRIPTION
**Pull request by m3d**
There was a problem with "aalborg" with close sharp turns. Currently we have original track width enlarged to 100m, so the vehicle can find the way back to original track. This PR fixes it.

### CODE REVIEW

**Comment by zwn** [comment]
Do we have an issue for the problem we are fixing here? I am not sure I understand the problem so I'll try to rephrase it.

The current version of "nearest_segment" does not actually return nearest segment. It returns first segment that is closer than some distance. The fix goes over all segments and calculates distance to each and then picks the one closest. Did I get it right? If so, why do we test it with width of 100m? Why was there a problem with sharp turns and why don't we test it with sharp turns?

Is this in any way related to #22 (I guess not)? What happens when the track contains crossing? Do we care here or that will be a different fix?

**Comment by m3d** [comment]
Yes, it is related to #22 but it actually fixes only part of it.

You are right, that width is no longer needed and the caller can decide what to do. Never-the-less I would keep variable ``width`` as part of Track.

**Comment by zwn** [comment]
We need `width` as part of Track because that is the driveable area (asphalt). I was not suggesting to remove it. But I have other issues:

1. I wonder why we test it with width=100 while the width plays no role in finding the closest segment.
2. I wonder why we don't test with sharp turns when that was the aim of the fix (as per the description of this PR)

**Comment by m3d** [comment]
The test was "failing example" of former approach, where `width` was input parameter. I will prepare fix.

The older solution failed in sharp curves because of the 100m parameter, not because of the sharp turns.

**Comment by zwn** [comment]
So we are fixing a problem when sometimes the old implementation found no nearest segment. Right?
In that case I think we need a test that exhibits this problem (and fails). I would just ignore everything around that "100m thing and sharp corners" as that probably confused me.

**Comment by m3d** [comment]
Fixed

**Comment by zwn** [comment]
Does it mean that `nearest_segment` can never return `None, None` now? One segment is always the nearest one... Just trying to understand more.

**Comment by m3d** [comment]
It could still return ``None, None`` not only in case of zero segments but also when the position is "outside of the scope" for given segment. For example if it would be only a line and the position would before or after the line segment you would receive ``None, None``. For the valid closed loop track you should get always values other than ``None, None``.

**Comment by m3d** [comment]
I added extra "fix" - it is no longer necessary to have wider track ...

If it is OK, should I squash it? Or do you want to try "squash & merge"? Feel free - I do not plan to work on pyroborace until tomorrow ...

**Comment by zwn** [comment]
> It could still return None, None not only in case of zero segments but also when the position is "outside of the scope" for given segment. For example if it would be only a line and the position would be before or after the line segment you should receive None, None. For the valid closed loop track you should get always values other than None, None.

This would make a nice addition to the doc-string of the method :wink:

**Comment by m3d** [comment]
:) OK, another fixup ...

**Pull request merged**
