### PR TITLE
Add tool for drawing track

### PR DESCRIPTION
**Pull request by m3d**
This is simplest version to draw track using matplotlib. The plan is to extend it to take into account track width and later draw logged car position data (offline, as post processing & analysis).

### CODE REVIEW

**Comment by m3d** [comment]
Good point. This `plot.py` is rather "tool" i.e. it is not necessarily "must have" (and I would keep it that way). So would you prefer to have folder "tools" and move it there with "requirements.txt"?
This script works fine with
```
>>> import matplotlib
>>> matplotlib.__version__
'1.4.2'
```

**Comment by zwn** [comment]
Just installing current matplotlib with pip from pypi (into virtualenv) does not work for me (btw: it installs around 6 dependent packages). Running the plot.py I get:
```
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
....
```
So, probably some special version combination of those packages is required. Providing `pip freeze` of your working environment can help big time.

**Comment by zwn** [comment]
I have found https://github.com/pypa/virtualenv/pull/888/files. After I have updated my copy of virtualenv from 15.0.1 to 15.1.0, it works :tada: . But let's add a proper requirements.txt anyway.

**Comment by zwn** [comment]
Let's use just _one_ requirements.txt in the root with all the dependencies. I'd rather not complicate the install instructions with multiple requirements.txt and tools directories and such. Thanks.

**Comment by zwn** [comment]
I've added the `requirements.txt` file. Please test it - even better - use it every day :wink:. For the tcl to work, you need to have virtualenv 15.1.0 installed in your system python. You can easily upgrade it by issuing `pip install --upgrade virtualenv`.

Can we have a simple test for `draw` that draws to a temporary png file? It does not need to check anything - just that it runs and no exception is thrown. That way we will be notified if we change the track structure to become incompatible with `draw`.

**Comment by m3d** [comment]
There is a unit test for plot.py now (with minor refactoring of plot.py in order to return figure and try to save it in test). It works fine for me locally but not on CI machines - can you please try to fix it?

**Comment by zwn** [comment]
I have no idea why it is trying to open a window in the travis build :disappointed:

**Comment by zwn** [comment]
But this may help http://stackoverflow.com/questions/2801882/generating-a-png-with-matplotlib-when-display-is-undefined

**Comment by m3d** [comment]
Whoow! Great, thanks a lot. So what now? Squash everything and merge? Or do you want to split it into several commits?

**Comment by zwn** [comment]
The last commit enables pip cache on travis. That should speed up the install there since it builds matplotlib from source. With that I am done. Feel free to squash everything - I wouldn't know how to split it so it makes sense anyway.

**Comment by zwn** [comment]
The next travis build hopefully won't take four and a half minutes.

**Comment by m3d** [comment]
rebased & swapped order ... please check both commits & now I would use "normal merge"

**Pull request merged**
