### PR TITLE
Fix/variable radius offset

### PR DESCRIPTION
**Pull request by m3d**

### CODE REVIEW

**Comment by zwn** [comment]
While your calculations might be correct, I am not able to decipher, if the are equivalent to what Speed Dreams does :frowning_face:. I am looking at [track4.cpp#L156](https://github.com/robotika/Roborace-Dreams/blob/56a8771d1ab385c4c81677ee66a46686749b3135/src/modules/track/trackv1/track4.cpp#L1568) where a new center location is recalculated for each subsegment using the current radius. The current radius is linear interpolation between radius and radiusend and somehow splines enter the picture there too. Your code expects a single center location for the whole segment so it seems different but I do not have such a deep understanding of both codes to say so for sure.

Do you have any tests that would support the equivalence of your code and Speed Dreams implementation of the variable radius stuff?

**Comment by m3d** [comment]
No, at the moment I have only "drive test" with "Espie loop" which we both know is not sufficient - but it is improvement (for that particular loop). OTOH the track loop still does  not always "close" (i.e. start and end are not identical positions), for example "Brondehach" and the reason could be your explanation.

**Comment by zwn** [comment]
The driving part is great :+1:. I created the #21 to track the problem and I am about to merge this.

**Comment by m3d** [comment]
You was right and I was wrong (totally). [espie.xml](https://github.com/robotika/Roborace-Dreams/blob/56a8771d1ab385c4c81677ee66a46686749b3135/data/tracks/circuit/espie/espie.xml) as well as [aalborg.xml](https://github.com/robotika/Roborace-Dreams/blob/56a8771d1ab385c4c81677ee66a46686749b3135/data/tracks/circuit/aalborg/aalborg.xml) do not contain any "end radius", i.e. there is no variable radius. So at the end this PR really only improved driving on tracks with normal turns only(!).

**Comment by zwn** [comment]
I was wondering why you put the two changes into one PR :smiley:

**Pull request merged**
