### PR TITLE
Feature/logging

### PR DESCRIPTION
**Pull request by m3d**
This is preliminary draft of I/O logging. At the moment there are data only logged with simple format: header with version and INPUT/OUTPUT header with packet length and packet data.

All logs are stored in "logs" directory and prefixed with name of the circuit.
For example `logs\espie-161208_194905.log` (size 16.2MB for 2 laps).

Relates to #8 

Should we add `--nologs` option? By default log everything? Is format OK for version 1 or do we need communication timestamps?

### CODE REVIEW

**Comment by m3d** [comment]
I just noticed that in Apyros I named similar class LogIO, here IOLog :) ... oh well.

Now I am working on higher level interpretation - so here should be another commit today, I hope.

**Comment by m3d** [comment]
Added another example how logfile can be used. I was not quite sure about
`from packets import sensors_gen` in "plot.py" but it is easier to pass the filename of the logfile directly (without any intermediate (x,y) text files). Also multiple trajectories are planned for comparison on the picture.

**Comment by m3d** [comment]
@zwn let me know if to proceed, or drop last commit(s). The next step would be refactoring "demo.py" to use Command and Sensors from packets and experiment with speed limits. In particular I need confirmation about:
* log format for version 1
* filenames (iolog.py, packets.py)
* class names (Command, Sensors in packets.py)
* variables in Command/Sensors ... i.e. should we have our own, or cover 1:1 original packet description?

**Comment by zwn** [comment]
Just a really quick run through:

- log format - I was thinking about switching the positions of `packet_type` and `size` making the `size` the only required field but I don't have a strong preference either way, so unless you do, it is ok the way it is
- filenames are fine
- class names are fine as well
- variables - I would add things as they are needed (along with tests) - covering 1:1 the original packets has a little value

Please continue :+1: and don't add intermediary txt files between the logs and the visualizations. I'd like to have one primary format (either txt or bin) that is used everywhere so I like you current approach.

In the future I'd like to add another `packet_type` beside `INPUT` and `OUTPUT` and place it at the beginning of each logfile. This packet would be a description of the other packets (the equivalent of DBC for CAN). For other robots/projects it would be a current configuration of the robot (like "what is the reference position of the lidar?"). But this can wait. Maybe one thing - can we in general not assert on unknown packet types? Or do you think that is a bad idea? 

My long term aim is to be able to share at least the visualization tools among projects and people and I'd like to have enough info in the log file to support it. Let's say the first visualization is position of the robot. The metapacket would contain information about how to decode the position to be ploted from the packets in the file. Then no matter the robot or author, the tool would plot the position/path of the robot.

**Comment by m3d** [comment]
> log format - I was thinking about switching the positions of packet_type and size making the size the only required field but I don't have a strong preference either way, so unless you do, it is ok the way it is

Good point. I wanted to have the "message size" same as the original packet, but there is no need for it. Moreover your suggestion enables packets like "INPUT_WITH_TIMESTAMP" so there can be extra (larger) header. For comparison see pcap:
https://github.com/kisom/pypcapfile/blob/master/pcapfile/savefile.py#L218
```
(timestamp, timestamp_us, capture_len, packet_len) = packet_header
```
I will swap it.

I agree with extra types besides `INPUT` and `OUTPUT` ... in particular I miss "description packet" of current run. From this point I agree that unknown packet types should be skipped/ignored and not asserted.

The long term goal is a bit difficult. If you want to skip intermediate files you need to introduce something like "interpreters", i.e. piece of code which can translate absolute XY, position from "sensors packet with offset 44 bytes decoded as float".

**Comment by m3d** [comment]
Maybe one more detail:
```
io_dir, length = unpack('HH', data)
```
is 16bit length sufficient now now? I would say "yes" for pyroborace and that it can be later changed to 32bit (with changing major version), OK?

**Comment by zwn** [comment]
I was thinking the same.

**Comment by m3d** [comment]
Oops, I did my "favorite mistake" :(. There were 3 patches need, so I started with interactive rebase ... and the "problem" is ... the length should contain the length of data OR data + header OR data + header + length bytes itself? I.e. can you have empty packet without type and that would be 00 02 (I am not sure about endians at the moment), with type it would be 00 04 00 42 and with single byte 0x01 then 00 05 00 42 01?

**Comment by zwn** [comment]
I think down at the bottom it should allow this pattern:

```python
while not logfile.eof():
   len = logfile.read(2)
   data = logfile.read(len)
```

One level up in the abstraction can be the socket wrapper that uses the data store above. So it gets packet from the socket and constructs `data` to be saved in the store (by prepending type and/or timestamp). When reading, the socket wrapper asks for next `data` and the underlying log just returns it (the socket wrapper never sees how it is stored). So the log is just a stream of packets without concerning itself with anything else. 

```python
for data in log:
    print data
```

Now the socket wrapper unwraps `data` and gets whatever it stored there before.

Does it make sense?

**Comment by m3d** [comment]
Well, yes & no. I rebased the code and there are plenty of +/- 2, which I do not like. Feel free to suggest code patches. Or we will merge this and then do the log refactoring?

**Pull request merged**
